"""Conversation-routing corpus — adversarial cases generated by an agent panel, human-verified here.

These lock the spoken-routing decisions that misfired in the field: a greeting must not be heard as a
command, a build instruction that merely contains "stop"/"goodbye" must not be swallowed as an
interrupt/sign-off, and a half-built-cleanup answer must never delete on anything but a clean yes.
Labels are the CORRECT expected behaviour (some generator labels were fixed; ambiguous "helix-as-a-word"
cases were dropped).
"""
from __future__ import annotations

import pytest

from helix.ui.console_view import _cleanup_answer
from helix.ui.voice import is_dismissal, is_stop, split_wake

# (text, addressed) — is the user addressing HELIX? Only the routing bit is asserted (command extraction
# is covered in test_voice). Ambiguous sentences where "helix" is a normal word are intentionally excluded.
WAKE = [
    ("HELIX are you there", True), ("hey helix you awake", True), ("helix can you hear me", True),
    ("okay helix hello", True), ("helix", True), ("HELIX!", True), ("hey, helix... are you awake", True),
    ("helix build me a stopwatch app", True), ("okay helix what time is it", True),
    ("so anyway helix what is the weather", True), ("helix, goodbye", True),
    ("helics open the notes app", True), ("heelix can you hear me", True),
    ("healix turn on the lights", True), ("helex play some music", True),
    ("helux set a timer for ten minutes", True), ("heelux are you listening", True),
    ("helicks whats on my calendar", True), ("hilux add milk to my list", True),
    ("you there?", False), ("hello", False), ("he likes building things", False),
    ("i feel relaxed today", False), ("tell me about the city of phoenix arizona", False),
    ("a healthy breakfast is important", False), ("the helicopter is loud", False),
    ("hey lex play a song", False),
]

# (text, is_stop) — a SHORT standalone stop command vs. a request that merely mentions stopping.
STOP = [
    ("stop", True), ("stop.", True), ("Stop!", True), ("stop it", True), ("stop talking", True),
    ("stop now", True), ("stop please", True), ("okay stop", True), ("no no stop", True),
    ("be quiet", True), ("shut up", True), ("hush", True), ("shush", True), ("never mind", True),
    ("nevermind", True), ("cancel that", True), ("that's enough", True), ("enough", True),
    ("quiet", True), ("stop stop stop", True), ("um stop talking please", True),
    ("build a stopwatch", False), ("make me a stop watch app", False),
    ("build a stop sign detector app", False), ("design a bus stop finder for my commute", False),
    ("the cancelled orders should show up in red", False),
    ("can you cancel that subscription for me when you get a chance", False),
    ("add a stop button to the timer", False), ("where is the nearest train stop", False),
    ("that is enough seating for everyone at the table", False),
    ("I need a quiet hours scheduler for the house", False),
    ("make the next stop on the route flash on the map", False),
]

# (text, is_dismissal) — ends the session, vs. a request that merely contains a sign-off word.
DISMISS = [
    ("goodbye", True), ("okay goodbye helix talk to you later", True), ("alright bye", True),
    ("bye now", True), ("that's all for now", True), ("thats all thank you", True),
    ("thanks helix", True), ("thank you helix that was great", True), ("brb", True),
    ("be right back gotta grab the door", True), ("i'll be back in a sec", True),
    ("good bye see ya", True),
    ("hello", False), ("one moment", False), ("thanks for that", False),
    ("thank you so much that's perfect", False),
    ("build me a goodbye card generator app", False),       # a build request, not a sign-off
    ("can you make an app that says bye to people when they leave a meeting", False),
    ("add a goodbye message screen to the app", False),
    ("i think that's all wrong, fix the layout", False),    # a fix request, not a sign-off
    ("okay perfect i'm done for today", False), ("see you later helix", False),
    ("later", False), ("that is all i needed", False),
]

# (text, answer) — reply to "remove the half-built X?"; 'neither' and 'no' both KEEP the work (safe).
YESNO = [
    ("yes", "yes"), ("yeah remove it", "yes"), ("yep go ahead and get rid of it", "yes"),
    ("sure", "yes"), ("uh huh delete it please", "yes"), ("yes please trash it", "yes"),
    ("go ahead", "yes"), ("remove it", "yes"),
    ("no", "no"), ("no keep it", "no"), ("nah leave it alone", "no"), ("don't", "no"),
    ("no don't remove it", "no"), ("leave it where it is", "no"), ("nope hang on to it for now", "no"),
    ("actually keep that one", "no"),
    ("wait what was it building again", "neither"), ("build me a stopwatch instead", "neither"),
    ("what's the weather", "neither"), ("can you finish it instead of deleting it", "neither"),
    ("hmm not sure", "neither"), ("why did it stop in the first place", "neither"),
]


@pytest.mark.parametrize("text,addressed", WAKE)
def test_wake_routing(text, addressed):
    assert split_wake(text)[0] is addressed, text


@pytest.mark.parametrize("text,expected", STOP)
def test_stop_routing(text, expected):
    assert is_stop(text) is expected, text


@pytest.mark.parametrize("text,expected", DISMISS)
def test_dismissal_routing(text, expected):
    assert is_dismissal(text) is expected, text


@pytest.mark.parametrize("text,expected", YESNO)
def test_cleanup_answer_routing(text, expected):
    assert _cleanup_answer(text) == expected, text
