"""Persistence ports — settings (JSON), memory + conversation (SQLite)."""
from __future__ import annotations

from typing import Any, Protocol

from helix.domain.models import Message, Version


class SettingsStore(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...

    def set(self, key: str, value: Any) -> None: ...

    def all(self) -> dict[str, Any]: ...


class MemoryStore(Protocol):
    def record_usage(self, input_tokens: int, output_tokens: int, cost_usd: float) -> None: ...

    def total_cost(self) -> float: ...

    def add_version(self, version: Version) -> None: ...

    def versions(self) -> list[Version]: ...

    def set_pinned(self, commit: str) -> None: ...


class ConversationStore(Protocol):
    def append(self, message: Message) -> None: ...

    def recent(self, limit: int = 100) -> list[Message]: ...

    def clear(self) -> None: ...
